import Head from "next/head";
import Link from "next/link";
import styles from "../../styles/Home.module.css";

const Product = (): JSX.Element => {
  return (
    <div className={styles.main} style={{ background: "#f1f1f1" }}>
      <Head>
        <title>Product detail | MasterJi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Product detail</h1>
      <Link href={"about"} className="btn btn-purple mg-bt-2">
        Products
      </Link>
      <div className="product">
        <div className="images">
          <img
            className="product-img"
            src="https://via.placeholder.com/540/92c952"
            alt="products"
          />
          <div className="list-thumbnail">
            <img
              src="https://via.placeholder.com/100/f9cee5"
              alt="image products thumbnail"
            />
            <img
              src="https://via.placeholder.com/100/f9cee5"
              alt="image products thumbnail"
            />
            <img
              src="https://via.placeholder.com/100/f9cee5"
              alt="image products thumbnail"
            />
            <img
              src="https://via.placeholder.com/100/f9cee5"
              alt="image products thumbnail"
            />
            <img
              src="https://via.placeholder.com/100/f9cee5"
              alt="image products thumbnail"
            />
          </div>
        </div>
        <div className="product-content">
          <div className="product-button"></div>

          <div className="btn mg-bt-1 btn-purple">add to cart</div>
          <div className="btn mg-bt-2 btn-red">buy now</div>
          <div className="product-price mg-bt-2">
            <span className="price discount">77.000(đ)</span>
            <span className="price">35.000(đ)</span>
            <span className="discount"></span>
          </div>
          <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Harum animi
            sunt error inventore accusamus mollitia, optio nemo sed doloribus
            iste illo perferendis maxime aperiam dolore sapiente asperiores
            laborum cupiditate culpa.
          </p>
          <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Harum animi
            sunt error inventore accusamus mollitia, optio nemo sed doloribus
            iste illo perferendis maxime aperiam dolore sapiente asperiores
            laborum cupiditate culpa.
          </p>

          <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Harum animi
            sunt error inventore accusamus mollitia, optio nemo sed doloribus
            iste illo perferendis maxime aperiam dolore sapiente asperiores
            laborum cupiditate culpa.
          </p>

          <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Harum animi
            sunt error inventore accusamus mollitia, optio nemo sed doloribus
            iste illo perferendis maxime aperiam dolore sapiente asperiores
            laborum cupiditate culpa.
          </p>

          <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Harum animi
            sunt error inventore accusamus mollitia, optio nemo sed doloribus
            iste illo perferendis maxime aperiam dolore sapiente asperiores
            laborum cupiditate culpa.
          </p>

          {/* <input type="text" placeholder="Quantity" /> */}
        </div>
      </div>
    </div>
  );
};
export default Product;
