import Head from "next/head";
import Link from "next/link";
import styles from "../../styles/Home.module.css";

const About = (props: any): JSX.Element => {
  return (
    <div className={styles.main}>
      <Head>
        <title>List image | MasterJi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>images</h1>
      <Link href={"/"}>
        <button className="btn"> go to home</button>
      </Link>
      <div className="list-img">
        {props.data.map(
          (item: any, index: number) =>
            index < 100 && (
              <div className="img-item">
                <img key={index} src={item.url} alt={item.title} />
              </div>
            )
        )}
      </div>
    </div>
  );
};

export async function getServerSideProps() {
  const data = await loadPosts();
  return { props: { data } };
}

export async function loadPosts() {
  const res = await fetch("https://jsonplaceholder.typicode.com/photos");
  const data = await res.json();

  return data;
}
export default About;
